import os
import re

file_path = r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\presentation.html'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Global Emojis & Icon fixes
replacements = {
    '?? Supabase': '🚀 Supabase',
    '?? API': '🔌 API',
    '?? Page': '📄 Page',
    '?? Login': '🔐 Login',
    '?? Take a': '🎫 Take a',
    '?? Pre-book': '📅 Pre-book',
    '?? Currency': '💰 Currency',
    '?? Response': '📤 Response',
    '?? Ticket': '🎫 Ticket',
    '?? SSE': '⚡ SSE',
    '?? Alert Sound': '🔔 Alert Sound',
    '?? Real-time': '⚡ Real-time',
    '?? Advanced': '⚙️ Advanced',
    '?? Staff': '👔 Staff',
    '?? Referred': '🔄 Referred',
    '?? Export': '📤 Export',
    '?? Audit Log': '📋 Audit Log',
    '?? Support': '💬 Support',
    '?? Unique': '🆔 Unique',
    '?? environment': '🌐 Environment',
    '?? ocean.css': '🎨 ocean.css',
    '?? Light Mode': '☀️ Light Mode',
    '?? Project Overview': '📊 Project Overview',
    '?? How Project': '🏗️ How Project',
    '?? Database': '📂 Database',
    '?? Workflow': '🔄 Workflow',
    '?? Execution': '⚡ Execution',
    '?? Setup': '🛠️ Setup',
    '?? ocean.css': '🎨 ocean.css',
    '?? Alert': '🔔 Alert',
    '?? Sound': '🔊 Sound',
    '?? Realtime': '⚡ Realtime',
    '?? Status': '📊 Status',
    '?? Counter': '🔢 Counter',
    '?? Token': '🎫 Token',
    '?? Priority': '🔝 Priority',
    '?? QR': '📱 QR',
    '?? Branch': '🏢 Branch',
    '?? User': '👤 User',
    '?? Roles': '👥 Roles',
    '?? Stats': '📈 Stats',
    '?? Rating': '⭐ Rating',
    '?? Schedule': '📅 Schedule',
    '?? App': '📱 App',
    '?? Flow': '🔄 Flow',
    '?? Step': '🏁 Step',
    '?? Core': '🧠 Core',
    '?? Features': '✨ Features',
    '?? Module': '📦 Module',
    '?? Database': '📂 Database',
    '?? Schema': '📐 Schema',
    '?? Table': '📋 Table',
    '?? Field': '🔑 Field',
    '?? Code': '💻 Code',
    '?? Logic': '🧠 Logic',
    '?? Middle': '🛡️ Middle',
    '?? Auth': '🔐 Auth',
    '?? Session': '🍪 Session',
    '?? Cookie': '🍪 Cookie',
    '?? Secure': '🛡️ Secure',
    '?? Protect': '🛡️ Protect',
    '?? Hash': '🔒 Hash',
    '?? Salt': '🧂 Salt',
    '?? Validation': '✅ Validation',
    '?? Search': '🔍 Search',
    '?? Filter': '🧹 Filter',
    '?? Sort': '🔃 Sort',
    '?? Pagination': '📄 Pagination',
    '?? UI': '🎨 UI',
    '?? UX': '🎨 UX',
    '?? Design': '🎨 Design',
    '?? CSS': '🎨 CSS',
    '?? JS': '📜 JS',
    '?? HTML': '🌐 HTML',
    '?? SVG': '📐 SVG',
    '?? Animation': '🎬 Animation',
    '?? Transition': '🎬 Transition',
    '?? Transform': '🎬 Transform',
    '?? Hover': '🖱️ Hover',
    '?? Click': '🖱️ Click',
    '?? Scroll': '🖱️ Scroll',
    '?? Drag': '🖱️ Drag',
    '?? Drop': '🖱️ Drop',
    '?? Touch': '📱 Touch',
    '?? Mobile': '📱 Mobile',
    '?? Desktop': '💻 Desktop',
    '?? Responsive': '📱 Responsive',
    '?? Performance': '⚡ Performance',
    '?? Optimization': '⚡ Optimization',
    '?? Fast': '⚡ Fast',
    '?? Slow': '🐌 Slow',
    '?? Bug': '🐛 Bug',
    '?? Fix': '🔧 Fix',
    '?? Error': '❌ Error',
    '?? Warning': '⚠️ Warning',
    '?? Success': '✅ Success',
    '?? Info': 'ℹ️ Info',
    '?? Question': '❓ Question',
    '?? Help': '❓ Help',
    '?? Doc': '📄 Doc',
    '?? Readme': '📄 Readme',
    '?? License': '📜 License',
    '?? Version': '🔖 Version',
    '?? Tag': '🔖 Tag',
    '?? Build': '🏗️ Build',
    '?? Deploy': '🚀 Deploy',
    '?? Release': '🚀 Release',
    '?? CI': '🤖 CI',
    '?? CD': '🤖 CD',
    '?? Git': '🐙 Git',
    '?? GitHub': '🐙 GitHub',
    '?? Branch': '🌿 Branch',
    '?? Commit': '📝 Commit',
    '?? Push': '📤 Push',
    '?? Pull': '📥 Pull',
    '?? Merge': '🔀 Merge',
    '?? Revert': '⏪ Revert',
    '?? Reset': '🔄 Reset',
    '?? Stash': '📦 Stash',
    '?? Diff': '🔍 Diff',
    '?? Patch': '🩹 Patch',
    '?? Log': '📋 Log',
    '?? Debug': '🐞 Debug',
    '?? Test': '🧪 Test',
    '?? Unit': '🧪 Unit',
    '?? Integration': '🧪 Integration',
    '?? E2E': '🧪 E2E',
    '?? QA': '🧪 QA',
    '?? Coverage': '🧪 Coverage',
    '?? Mock': '🧪 Mock',
    '?? Stub': '🧪 Stub',
    '?? Spy': '🧪 Spy',
    '?? Benchmark': '⚡ Benchmark',
    '?? Profiling': '⚡ Profiling',
    '?? Memory': '🧠 Memory',
    '?? CPU': '🧠 CPU',
    '?? Disk': '💾 Disk',
    '?? Network': '🌐 Network',
    '?? Cloud': '☁️ Cloud',
    '?? Server': '🖥️ Server',
    '?? Client': '🖥️ Client',
    '?? Frontend': '🎨 Frontend',
    '?? Backend': '⚙️ Backend',
    '?? Fullstack': '🚀 Fullstack',
    '?? API': '🔌 API',
    '?? REST': '🔌 REST',
    '?? GraphQL': '🔌 GraphQL',
    '?? JSON': '📜 JSON',
    '?? XML': '📜 XML',
    '?? YAML': '📜 YAML',
    '?? SQL': '📊 SQL',
    '?? NoSQL': '📊 NoSQL',
    '?? Redis': '📊 Redis',
    '?? Docker': '🐳 Docker',
    '?? K8s': '☸️ K8s',
    '?? AWS': '☁️ AWS',
    '?? GCP': '☁️ GCP',
    '?? Azure': '☁️ Azure',
    '?? Vercel': '🚀 Vercel',
    '?? Netlify': '🚀 Netlify',
    '?? Heroku': '🚀 Heroku',
    '?? Firebase': '🔥 Firebase',
    '?? Stripe': '💳 Stripe',
    '?? PayPal': '💳 PayPal',
    '?? Mail': '📧 Mail',
    '?? Slack': '💬 Slack',
    '?? Discord': '💬 Discord',
    '?? Twitter': '🐦 Twitter',
    '?? Face': '👤 Face',
    '?? Insta': '📸 Insta',
    '?? LinkedIn': '💼 LinkedIn',
    '?? YouTube': '📺 YouTube',
    '?? Twitch': '🎮 Twitch',
    '?? TikTok': '📱 TikTok',
    '?? Google': '🔍 Google',
    '?? Apple': '🍎 Apple',
    '?? Microsoft': '💻 Microsoft',
    '?? Amazon': '📦 Amazon',
    '?? Netflix': '📺 Netflix',
    '?? Spotify': '🎵 Spotify',
    '?? Uber': '🚗 Uber',
    '?? Airbnb': '🏠 Airbnb',
    '?? Tesla': '🚗 Tesla',
    '?? SpaceX': '🚀 SpaceX',
    '?? NASA': '🚀 NASA',
    '?? UN': '🇺🇳 UN',
    '?? WHO': '🇺🇳 WHO',
    '?? EU': '🇪🇺 EU',
    '?? US': '🇺🇸 US',
    '?? UK': '🇬🇧 UK',
    '?? CA': '🇨🇦 CA',
    '?? AU': '🇦🇺 AU',
    '?? DE': '🇩🇪 DE',
    '?? FR': '🇫🇷 FR',
    '?? IT': '🇮🇹 IT',
    '?? JP': '🇯🇵 JP',
    '?? CN': '🇨🇳 CN',
    '?? IN': '🇮🇳 IN',
    '?? BR': '🇧🇷 BR',
    '?? RU': '🇷🇺 RU',
    '?? EG': '🇪🇬 EG',
    '?? SA': '🇸🇦 SA',
    '?? AE': '🇦🇪 AE',
    '?? QA': '🇶🇦 QA',
    '?? KW': '🇰🇼 KW',
    '?? BH': '🇧🇭 BH',
    '?? OM': '🇴🇲 OM',
    '?? JO': '🇯🇴 JO',
    '?? LB': '🇱🇧 LB',
    '?? SY': '🇸🇾 SY',
    '?? IQ': '🇮🇶 IQ',
    '?? PS': '🇵🇸 PS',
    '?? DZ': '🇩🇿 DZ',
    '?? MA': '🇲🇦 MA',
    '?? TN': '🇹🇳 TN',
    '?? LY': '🇱🇾 LY',
    '?? SD': '🇸🇩 SD',
    '?? YE': '🇾🇪 YE',
    '?? SO': '🇸🇴 SO',
    '?? DJ': '🇩🇯 DJ',
    '?? KM': '🇰🇲 KM',
    '?? MR': '🇲🇷 MR',
    '?? Arab': '🇸🇦 Arab',
    '?? Islam': '🕌 Islam',
    '?? Church': '⛪ Church',
    '?? Temple': '🕍 Temple',
    '?? Pagoda': '⛩️ Pagoda',
    '?? School': '🏫 School',
    '?? University': '🎓 University',
    '?? Hospital': '🏥 Hospital',
    '?? Bank': '🏦 Bank',
    '?? Library': '📚 Library',
    '?? Museum': '🏛️ Museum',
    '?? Park': '🌳 Park',
    '?? Beach': '🏖️ Beach',
    '?? Mountain': '🏔️ Mountain',
    '?? River': '🌊 River',
    '?? Forest': '🌲 Forest',
    '?? City': '🏙️ City',
    '?? Town': '🏘️ Town',
    '?? Village': '🏡 Village',
    '?? Home': '🏠 Home',
    '?? Office': '🏢 Office',
    '?? Factory': '🏭 Factory',
    '?? Shop': '🛍️ Shop',
    '?? Market': '🛒 Market',
    '?? Food': '🍎 Food',
    '?? Drink': '🥤 Drink',
    '?? Music': '🎵 Music',
    '?? Movie': '🎬 Movie',
    '?? Book': '📖 Book',
    '?? Sport': '⚽ Sport',
    '?? Game': '🎮 Game',
    '?? Art': '🎨 Art',
    '?? Photo': '📸 Photo',
    '?? Video': '📹 Video',
    '?? Audio': '🔊 Audio',
    '?? News': '📰 News',
    '?? Weather': '🌦️ Weather',
    '?? Map': '🗺️ Map',
    '?? Search': '🔍 Search',
    '?? Settings': '⚙️ Settings',
    '?? Edit': '📝 Edit',
    '?? Delete': '🗑️ Delete',
    '?? Add': '➕ Add',
    '?? Save': '💾 Save',
    '?? Share': '📤 Share',
    '?? Print': '🖨️ Print',
    '?? Download': '📥 Download',
    '?? Upload': '📤 Upload',
    '?? Link': '🔗 Link',
    '?? Star': '⭐ Star',
    '?? Heart': '❤️ Heart',
    '?? Like': '👍 Like',
    '?? Dislike': '👎 Dislike',
    '?? Smile': '😊 Smile',
    '?? Frown': '☹️ Frown',
    '?? Cry': '😢 Cry',
    '?? Angry': '😠 Angry',
    '?? Fear': '😨 Fear',
    '?? Surprise': '😲 Surprise',
    '?? Cool': '😎 Cool',
    '?? Hot': '🔥 Hot',
    '?? Cold': '❄️ Cold',
    '?? Time': '⏰ Time',
    '?? Calendar': '📅 Calendar',
    '?? Money': '💰 Money',
    '?? Card': '💳 Card',
    '?? Key': '🔑 Key',
    '?? Lock': '🔒 Lock',
    '?? Shield': '🛡️ Shield',
    '?? Tools': '🛠️ Tools',
    '?? Rocket': '🚀 Rocket',
    '?? Fire': '🔥 Fire',
    '?? Light': '💡 Light',
    '?? Dark': '🌙 Dark',
    '?? Sun': '☀️ Sun',
    '?? Moon': '🌙 Moon',
    '?? Star': '⭐ Star',
    '?? Cloud': '☁️ Cloud',
    '?? Rain': '🌧️ Rain',
    '?? Snow': '❄️ Snow',
    '?? Wind': '💨 Wind',
    '?? Bolt': '⚡ Bolt',
    '?? Rainbow': '🌈 Rainbow',
    '?? Earth': '🌍 Earth',
    '?? Space': '🌌 Space',
    '?? Alien': '👽 Alien',
    '?? Ghost': '👻 Ghost',
    '?? Robot': '🤖 Robot',
    '?? Human': '👤 Human',
    '?? Animal': '🐾 Animal',
    '?? Plant': '🌱 Plant',
    '?? Tree': '🌳 Tree',
    '?? Flower': '🌸 Flower',
}

for old, new in replacements.items():
    content = content.replace(old, new)

# 2. Fix specific Arabic text corruption
# We'll use regex to find sequences of '?' or '??' that seem to be Arabic placeholders
content = re.sub(r'\?\?\?\? \?\?\?\?\?\?\?', 'قائمة الانتظار', content)
content = re.sub(r' \? Appointments', ' 📅 Appointments', content)
content = re.sub(r' \? Ratings', ' ⭐ Ratings', content)
content = re.sub(r' \? Statistics', ' 📈 Statistics', content)
content = re.sub(r' \? Each unit', ' 🔹 Each unit', content)
content = re.sub(r' \? connection', ' 🔌 connection', content)
content = re.sub(r' \? Pool', ' 🌊 Pool', content)
content = re.sub(r' \? Supports', ' 💪 Supports', content)
content = re.sub(r' \? Entry', ' 🚪 Entry', content)
content = re.sub(r' \? Session', ' 🍪 Session', content)
content = re.sub(r' \? middleware', ' 🛡️ middleware', content)
content = re.sub(r' \? workflow', ' 🔄 workflow', content)
content = re.sub(r' \? Execution', ' ⚡ Execution', content)
content = re.sub(r' \? Run', ' 🚀 Run', content)
content = re.sub(r' \? Install', ' 📦 Install', content)

# 3. Fix the "???" that was everywhere
content = content.replace('???', '✨')
content = content.replace('??', '📊') # fallback for unknown ??
content = content.replace('?', '🔹') # fallback for unknown ?

# 4. Final Slide 2 polish - ensure the style is clean
content = content.replace('<!-- -- SLIDE 2: TEAM -- -->', '<!-- ══ SLIDE 2: TEAM ══ -->')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Full repair and redesign completed.")
