import re
import json

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\arabic_strings_admin.json', 'r', encoding='utf-8') as f:
    arabic_strings = json.load(f)

translations = {
    "الموظف": "Employee",
    "صفحة": "Page",
    "تصدير الطابور": "Export Queue",
    "خطأ": "Error",
    "السابق": "Previous",
    "لا توجد فروع": "No branches",
    "آخر": "Last",
    "الطلبات اليومية": "Daily Requests",
    "حذف السجلات الأقدم من": "Delete records older than",
    "ممتاز": "Excellent",
    "التليفون": "Phone",
    "توزيع الخدمات": "Services Distribution",
    "حذف القديم": "Delete Old",
    "ديسمبر": "December",
    "توزيع الأدوار": "Roles Distribution",
    "سجل العمليات": "Audit Log",
    "إجمالي العمليات لكل فرع": "Total operations per branch",
    "قائمة الفروع": "Branches List",
    "أكتوبر": "October",
    "مؤكد": "Confirmed",
    "محمد أحمد": "John Doe",
    "جدول الأيام": "Days Schedule",
    "تعديل الموظف": "Edit Employee",
    "جداول الموظفين": "Staff Schedules",
    "كلمة مرور جديدة": "New Password",
    "المواعيد": "Appointments",
    "غير محدد": "Not specified",
    "الموظفين": "Staff",
    "نوفمبر": "November",
    "البنك الذكي": "Smart Bank",
    "لا توجد سجلات": "No records",
    "خُدِموا": "Served",
    "كل المواعيد": "All Appointments",
    "إعادة تعيين": "Reset",
    "لوحة الإدارة": "Admin Panel",
    "حذف موظف": "Delete Employee",
    "الفروع": "Branches",
    "أيام": "Days",
    "موظف فرع": "Branch Employee",
    "فاضية": "Empty",
    "لا يوجد موظفون": "No employees",
    "لوحة التحكم": "Dashboard",
    "الموبايل": "Mobile",
    "القائمة": "Menu",
    "دقيقة": "Minute",
    "تركيبة الفريق": "Team Structure",
    "إضافة": "Add",
    "اسم المستخدم": "Username",
    "الخدمة": "Service",
    "سجل": "Record",
    "إضافة فرع جديد": "Add New Branch",
    "تقارير متقدمة": "Advanced Reports",
    "إجازة": "Leave",
    "المستخدم": "User",
    "اسم العميل": "Customer Name",
    "تقييم": "Rating",
    "متوسط وقت الانتظار": "Avg Wait Time",
    "مغلق": "Closed",
    "متوسط التقييم": "Avg Rating",
    "عمل": "Work",
    "بدون فرع": "No Branch",
    "تعديل الموعد": "Edit Appointment",
    "حذف": "Delete",
    "مفتوح": "Open",
    "من": "From",
    "حالة المواعيد": "Appointments Status",
    "فاتح": "Light",
    "تحديث": "Update",
    "أبريل": "April",
    "انتظار": "Waiting",
    "المشرف": "Admin",
    "فبراير": "February",
    "تحويل بنكي": "Bank Transfer",
    "تم خدمتهم": "Served",
    "يونيو": "June",
    "الاسم": "Name",
    "إيداع": "Deposit",
    "قائمة الموظفين": "Staff List",
    "مارس": "March",
    "إضافة موظف جديد": "Add New Employee",
    "مباشر": "Live",
    "تصدير المواعيد": "Export Appointments",
    "التحليلات": "Analytics",
    "القاهرة، المعادي": "Cairo, Maadi",
    "مرض": "Sick",
    "حذف فرع": "Delete Branch",
    "طلبات": "Requests",
    "لا توجد بيانات لهذا الشهر": "No data for this month",
    "مدير النظام": "System Admin",
    "سبتمبر": "September",
    "اليوم": "Today",
    "نشاط الفروع": "Branches Activity",
    "جاري التحميل": "Loading",
    "تسجيل الخروج": "Logout",
    "الدور": "Role",
    "عميل": "Customer",
    "في الطوابير": "In Queues",
    "بحث بالاسم أو المستخدم": "Search by name or user",
    "تصدير التقييمات": "Export Ratings",
    "مدير فرع": "Branch Manager",
    "إلغاء": "Cancel",
    "سحب": "Withdraw",
    "شاشة العرض": "Display Screen",
    "إجراءات": "Actions",
    "يناير": "January",
    "إعادة تعيين الطابور؟": "Reset Queue?",
    "تقييمات العملاء": "Customer Ratings",
    "التالي": "Next",
    "يوم؟": "Days?",
    "يوليو": "July",
    "حركة الطابور": "Queue Movement",
    "فرع المعادي": "Maadi Branch",
    "آخر التقييمات": "Recent Ratings",
    "ساعات": "Hours",
    "اختر": "Select",
    "تعديل": "Edit",
    "الموقع": "Location",
    "الإدارة": "Management",
    "الاسم الكامل": "Full Name",
    "أدخل الاسم واسم المستخدم": "Enter Name and Username",
    "عطلة": "Holiday",
    "الطوابير المباشرة": "Live Queues",
    "التاريخ": "Date",
    "داكن": "Dark",
    "جاري": "Processing",
    "الوقت": "Time",
    "كلمة المرور": "Password",
    "استفسار عام": "General Inquiry",
    "الطابور فاضي": "Queue is empty",
    "التنقل": "Navigation",
    "الحالة": "Status",
    "مريض": "Sick",
    "فتح حساب جديد": "Open New Account",
    "العمليات": "Operations",
    "متوسط التقييم لكل فرع": "Avg Rating per Branch",
    "الطوابير": "Queues",
    "الفرع": "Branch",
    "أغسطس": "August",
    "أدخل كل البيانات": "Enter all details",
    "ملاحظة": "Note",
    "لا توجد بيانات": "No data",
    "لا توجد مواعيد": "No appointments",
    "العميل": "Customer",
    "لا توجد تقييمات بعد": "No ratings yet",
    "طلب بطاقة": "Card Request",
    "بحث": "Search",
    "بحث بالاسم أو الخدمة": "Search by name or service",
    "حفظ": "Save",
    "مايو": "May",
    "تعديل الفرع": "Edit Branch",
    "لا توجد تقييمات": "No ratings",
    "اسم الفرع": "Branch Name",
    "المواعيد المحجوزة": "Booked Appointments",
    "إجمالي": "Total"
}

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\admin.html', 'r', encoding='utf-8') as f:
    html = f.read()

for ar, en in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
    html = html.replace(ar, en)

# Change html tag
html = html.replace('<html lang="ar" dir="rtl">', '<html lang="en" dir="ltr">')

# Also in admin.html, there's 'ar-EG'
html = html.replace("'ar-EG'", "'en-US'")

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\admin.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Translated admin.html successfully!")
