import re
import json

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\arabic_strings_manager.json', 'r', encoding='utf-8') as f:
    dict_manager = json.load(f)
with open(r'c:\Users\mahmi\Desktop\smart-service-hub\arabic_strings_teller.json', 'r', encoding='utf-8') as f:
    dict_teller = json.load(f)

translations = {
    "أداء الموظفين": "Staff Performance",
    "مُحال": "Referred",
    "مايو": "May",
    "حالة المواعيد": "Appointments Status",
    "السبت": "Saturday",
    "لا توجد حالات مُحالة حالياً": "No referred cases currently",
    "موظفو الفرع": "Branch Staff",
    "دقائق": "Mins",
    "أيام": "Days",
    "تأكيد": "Confirm",
    "عطلة": "Holiday",
    "الأحد": "Sunday",
    "منذ": "Since",
    "حالة مُحالة": "Referred Case",
    "التقييمات": "Ratings",
    "تعديل الموعد": "Edit Appointment",
    "اليوم": "Today",
    "لوحة مدير الفرع": "Branch Manager Dashboard",
    "بنجاح": "Successfully",
    "تم تحديث الموعد": "Appointment Updated",
    "ابحث باسم العميل أو الخدمة": "Search by customer name or service",
    "اسم العميل": "Customer Name",
    "العميل": "Customer",
    "يناير": "January",
    "محمد أحمد": "John Doe",
    "أغسطس": "August",
    "جاري التحميل": "Loading",
    "إرجاع للموظف": "Return to Teller",
    "انتظار": "Waiting",
    "تعديل بيانات الموظف": "Edit Employee Data",
    "الثيم الداكن": "Dark Theme",
    "تحديث": "Refresh",
    "الجداول": "Schedules",
    "إضافة موظف جديد": "Add New Employee",
    "مؤكد": "Confirmed",
    "خطأ في تحميل الموظفين": "Error loading staff",
    "لا توجد مواعيد": "No appointments",
    "خُدِموا اليوم": "Served Today",
    "الخدمة": "Service",
    "لا يوجد موظفون": "No employees",
    "يونيو": "June",
    "لا توجد بيانات": "No data",
    "حركة العملاء": "Customer Traffic",
    "حفظ التغييرات": "Save Changes",
    "الموظفون": "Staff",
    "الوقت": "Time",
    "نوع الخدمة": "Service Type",
    "نشط": "Active",
    "الاسم": "Name",
    "يوليو": "July",
    "أكتوبر": "October",
    "أدخل الاسم واسم المستخدم": "Enter Name and Username",
    "القائمة الرئيسية": "Main Menu",
    "حل": "Resolve",
    "عميل جديد في الطابور": "New customer in queue",
    "الحالات المُحالة من الموظفين": "Cases Referred by Tellers",
    "الجمعة": "Friday",
    "مكتمل": "Completed",
    "التاريخ": "Date",
    "مسح الكل": "Clear All",
    "المستخدم": "User",
    "نوفمبر": "November",
    "رقم الموبايل": "Mobile Number",
    "تم خدمة العميل": "Customer served",
    "منذ دقيقتين": "2 mins ago",
    "منذ ساعة": "1 hour ago",
    "خطأ": "Error",
    "لا توجد إشعارات": "No notifications",
    "إجازة": "Leave",
    "إجراءات": "Actions",
    "الثلاثاء": "Tuesday",
    "إضافة موظف": "Add Employee",
    "النظام يعمل بشكل طبيعي": "System operating normally",
    "تم حل الحالة": "Case resolved",
    "اسم المستخدم": "Username",
    "أبريل": "April",
    "موعد مُحال من الموظفين": "Appointment referred by tellers",
    "مدير": "Manager",
    "آخر": "Last",
    "الحالات المُحالة": "Referred Cases",
    "تم تأكيد موعد سارة محمود": "Sarah Mahmoud appointment confirmed",
    "الإشعارات": "Notifications",
    "مُحالة": "Referred",
    "البنك الذكي": "Smart Bank",
    "إحصائيات الفرع السريعة": "Quick Branch Stats",
    "الاسم الكامل": "Full Name",
    "سجل النشاط": "Activity Log",
    "مرض": "Sick",
    "منذ ساعتين": "2 hours ago",
    "عمل": "Work",
    "مواعيد الفرع اليوم": "Branch Appointments Today",
    "تقييمات العملاء": "Customer Ratings",
    "الموظف علي بدأ دوامه": "Employee Ali started his shift",
    "ديسمبر": "December",
    "الموظف": "Employee",
    "إعادة تعيين الطابور الصباحي": "Morning Queue Reset",
    "حذف موظف": "Delete Employee",
    "اتركه فارغاً للإبقاء": "Leave empty to keep",
    "تصدير": "Export",
    "إلغاء": "Cancel",
    "موظف": "Employee",
    "لا توجد تقييمات": "No ratings",
    "تم تأكيد موعد خالد أحمد": "Khaled Ahmed appointment confirmed",
    "تعديل": "Edit",
    "خُدِموا": "Served",
    "الآن": "Now",
    "تقييم": "Rating",
    "موعد جديد محجوز": "New appointment booked",
    "موظفون": "Staff",
    "الفرع": "Branch",
    "خطأ في تحميل المواعيد": "Error loading appointments",
    "العملاء المخدومون": "Served Customers",
    "إعادة تعيين الطابور بالكامل؟": "Reset the entire queue?",
    "في الانتظار": "Waiting",
    "الاثنين": "Monday",
    "جاري": "Processing",
    "سبتمبر": "September",
    "فبراير": "February",
    "الموبايل": "Mobile",
    "اختياري": "Optional",
    "تم تحديث بيانات الموظف": "Employee data updated",
    "حل الحالة": "Resolve Case",
    "الأربعاء": "Wednesday",
    "مواعيد اليوم": "Today's Appointments",
    "المواعيد": "Appointments",
    "الدور": "Role",
    "كلمة المرور الجديدة": "New Password",
    "الخميس": "Thursday",
    "كلمة المرور": "Password",
    "موظف فرع": "Branch Employee",
    "مريض": "Sick",
    "ملاحظة": "Note",
    "متوسط الانتظار": "Avg Wait",
    "كل شيء تحت السيطرة": "Everything is under control",
    "مدير فرع": "Branch Manager",
    "الثيم الفاتح": "Light Theme",
    "مدير الفرع": "Branch Manager",
    "خروج": "Logout",
    "مارس": "March",
    "ابحث باسم الموظف": "Search by employee name",
    "دقيقة": "Minute",
    "حالة مُحالة من الموظف": "Case referred by employee",
    "إدارة الفرع": "Branch Management",
    "أخرى": "Other",
    "جداول الموظفين": "Staff Schedules",
    "الحالة": "Status",
    "التحليلات": "Analytics",
    "خطأ في الاتصال": "Connection Error",

    # Teller strings
    "يُخدم الآن": "Serving Now",
    "شاشة الموظف": "Teller Screen",
    "طابور الانتظار": "Waiting Queue",
    "إحالة للمدير": "Refer to Manager",
    "بدء الخدمة": "Start Service",
    "اختر الخدمة أولاً": "Select service first",
    "عميل جديد": "New Customer",
    "الأدوات": "Tools",
    "تسجيل الخروج": "Logout",
    "إعادة": "Reset",
    "شاشة العرض": "Display Screen",
    "لا توجد مواعيد اليوم": "No appointments today",
    "تم خدمتهم": "Served",
    "إحصائيات اليوم": "Today's Stats",
    "إحالة هذا العميل لمدير الفرع؟": "Refer this customer to branch manager?",
    "استدعاء التالي": "Call Next",
    "عند المدير": "With Manager",
    "ذوي احتياجات": "Special Needs",
    "إضافة للطابور": "Add to Queue",
    "الطابور فاضي الآن": "Queue is empty now",
    "الطابور": "Queue",
    "تم إحالة الموعد للمدير": "Appointment referred to manager",
    "كبير السن": "Elderly",
    "تم إنهاء الموعد": "Appointment finished",
    "أولوية": "Priority",
    "مواعيد": "Appointments",
    "تم تأكيد الموعد": "Appointment confirmed",
    "إضافة تذكرة": "Add Ticket",
    "مُحالة للمدير": "Referred to Manager",
    "اختر الخدمة": "Choose Service",
    "تم إرجاع": "Returned",
    "من المدير": "From Manager",
    "التذكرة": "Ticket",
    "تأكيد إحالة هذا الموعد لمدير الفرع؟": "Confirm referral to branch manager?",
    "إنهاء الموعد": "Finish Appointment",
    "إنهاء": "Finish",
    "بدأت خدمة": "Started service",
    "أنهِ الموعد الحالي أولاً": "Finish current appointment first",
    "جاري خدمة موعد الآن": "Currently serving an appointment",
    "اضغط استدعاء التالي": "Click Call Next",
    "إنهاء الخدمة": "Finish Service",
    "لا يوجد عميل حالياً": "No customer currently",
    "عادي": "Normal",
    "إحالة": "Refer",
    "تم الخدمة": "Served"
}

for file_path in [r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\manager.html', r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\teller.html']:
    with open(file_path, 'r', encoding='utf-8') as f:
        html = f.read()

    for ar, en in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
        html = html.replace(ar, en)

    # Change html tag
    html = html.replace('<html lang="ar" dir="rtl">', '<html lang="en" dir="ltr">')

    html = html.replace("'ar-EG'", "'en-US'")

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(html)

print("Translated manager and teller successfully!")
