import re
import json

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\arabic_strings_customer.json', 'r', encoding='utf-8') as f:
    arabic_strings = json.load(f)

translations = {
    "رقم انتظار": "Queue Number",
    "وقت متوقع": "Expected Time",
    "كيف كانت تجربتك؟": "How was your experience?",
    "الطابور فاضي": "Queue is empty",
    "تقييمك يساعدنا على تحسين خدمتنا": "Your rating helps us improve our service",
    "ماذا تريد اليوم؟": "What do you want today?",
    "سحب": "Withdraw",
    "تابع": "Follow",
    "إيداع": "Deposit",
    "تم الحجز بنجاح": "Booked successfully",
    "عادي": "Normal",
    "إرسال التقييم": "Submit Rating",
    "نقاط": "Points",
    "محمد أحمد": "John Doe",
    "تعليقك": "Your comment",
    "أعلى": "Top",
    "دقيقة": "Minute",
    "أحسنت": "Well done",
    "جاهز": "Ready",
    "اسمك": "Your Name",
    "دولار": "Dollar",
    "إعاقة": "Disabled",
    "الخدمة": "Service",
    "امسح الكود لمتابعة رقمك": "Scan the code to track your number",
    "شكراً": "Thank you",
    "العب وانتظر": "Play & Wait",
    "أهلاً بك،": "Welcome,",
    "اضغط للطيران": "Tap to fly",
    "دخول الموظفين": "Staff Login",
    "في الانتظار": "Waiting",
    "رقم جديد": "New Number",
    "رقم قياسي": "High Score",
    "لا أحد يُخدم الآن": "No one is being served now",
    "اختر الخدمة": "Choose Service",
    "ين": "Yen",
    "كبير سن": "Elderly",
    "أسعار العملات اليوم": "Today's Currency Rates",
    "طلب بطاقة": "Card Request",
    "حجز موعد": "Book Appointment",
    "خذ رقم انتظار أو احجز موعدك في ثوانٍ": "Take a queue number or book an appointment in seconds",
    "حيوات": "Lives",
    "واو": "Wow",
    "تعذر التحميل": "Failed to load",
    "للطيران": "To fly",
    "الخدمات المصرفية الذكية": "Smart Banking Services",
    "من فضلك اختر الخدمة": "Please select a service",
    "موبايلك": "Your Mobile",
    "رقم الموبايل": "Mobile Number",
    "عر": "AR",
    "هذا رقمك": "This is your number",
    "جاري التحميل": "Loading",
    "يُرجى تقدم العميل صاحب الرقم": "Please proceed customer with number",
    "استفسار عام": "General Inquiry",
    "جديدة": "New",
    "حاول تاني": "Try again",
    "فتح حساب جديد": "Open New Account",
    "يُخدم الآن": "Serving Now",
    "إسترليني": "Sterling",
    "فرنك": "Franc",
    "اضغط على الكانفاس أو": "Click on canvas or",
    "خطأ في إرسال التقييم": "Error submitting rating",
    "من فضلك اختر تقييم": "Please select a rating",
    "مستوى": "Level",
    "طباعة": "Print",
    "يُرجى التوجه للكاونتر": "Please proceed to the counter",
    "ممتاز": "Excellent",
    "رقمك": "Your Number",
    "الصوت مكتوم": "Sound Muted",
    "سرعة": "Speed",
    "خذ رقم انتظار الآن": "Take queue number now",
    "الأولوية": "Priority",
    "التاريخ": "Date",
    "عميل": "Customer",
    "خطأ في الاتصال": "Connection Error",
    "العب مرة تانية": "Play again",
    "الطابور فاضي الآن": "Queue is empty now",
    "بدون تعب": "Without hassle",
    "اختر الفرع": "Choose Branch",
    "تم إرسال تقييمك": "Your rating has been submitted",
    "الوقت": "Time",
    "درهم": "Dirham",
    "البنك الذكي": "Smart Bank",
    "طاير": "Flying",
    "دينار": "Dinar",
    "ريال": "Riyal",
    "اضغط لعبة جديدة للبدء": "Click New Game to start",
    "الاسم الكامل": "Full Name",
    "باقي": "Remaining",
    "اختياري": "Optional",
    "حجز موعد جديد": "Book New Appointment",
    "رقمك جاهز": "Your number is ready",
    "يورو": "Euro",
    "تفضل من فضلك": "Please go ahead",
    "الفرع": "Branch",
    "بوابة العملاء": "Customer Portal",
    "فاتح": "Light",
    "الطابور المباشر": "Live Queue",
    "حالة": "Status",
    "تأكيد الحجز": "Confirm Booking",
    "الصوت شغال": "Sound On",
    "تحديث": "Refresh",
    "من فضلك أدخل كل البيانات": "Please enter all details",
    "موقع": "Location",
    "متوقف": "Stopped",
    "شاشة العرض": "Display Screen",
    "موقعك": "Your Location",
    "خطير": "Dangerous",
    "مكافأة": "Reward",
    "تم": "Done",
    "ابتلع الأكل واكسب نقاط": "Eat food and earn points",
    "تحويل بنكي": "Bank Transfer",
    "حالة الطابور": "Queue Status",
    "حياة": "Life",
    "إلى الكاونتر": "To the Counter",
    "شكراً على تقييمك": "Thank you for your rating",
    "الاسم بالكامل": "Full Name",
    "الرقم": "The Number",
    "قائمة الانتظار": "Waiting List"
}

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\customer.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Custom function to replace based on dictionary, we iterate through keys and replace.
# Sort keys by length descending to replace longest phrases first
for ar, en in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
    html = html.replace(ar, en)

# Change html tag
html = html.replace('<html lang="ar" dir="rtl">', '<html lang="en" dir="ltr">')

with open(r'c:\Users\mahmi\Desktop\smart-service-hub\public\pages\customer.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Translated customer.html successfully!")
